name: Auto-Increment Version on PR Merge

on:
  push:
    branches:
      - dev
  pull_request:
    types: [closed]
    branches:
      - dev

jobs:
  bump-version:
    runs-on: ubuntu-22.04
    permissions:
        contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Bump version
        run: |
          npm version minor -m "Bump version to %s"
          git push
          git push --tags