name: Auto-Increment Version on PR Merge

on:
  pull_request:
    types: [closed] # Solo cuando se cierra el PR
    branches:
      - main

permissions:
  contents: write # Permite commits y push con GITHUB_TOKEN

jobs:
  tag-release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      # Checkout del repo (usa GITHUB_TOKEN automáticamente)
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      # Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Instalar dependencias
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libglib2.0-dev libgtk-3-dev
          npm ci
      
      # Build Tauri
      - name: Build Tauri app
        run: npm run tauri build
        
      # Configurar Git
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      
      # Incrementar versión según rama base
      - name: Increment version
        run: |
          BRANCH="${{ github.event.pull_request.base.ref }}"
          echo "Merged into branch: $BRANCH"

          # Incrementar versión según rama
          if [[ "$BRANCH" == "main" ]]; then
            echo "Bumping minor version"
            npm version minor -m "Bump version to %s"
          fi

          # Subir commit y tags
          git push
          git push --tags

      # Create Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            src-tauri/target/release/just-flying
            src-tauri/target/release/bundle/appimage/just-flying_${{ github.run_number }}_amd64.AppImage
            src-tauri/target/release/bundle/deb/just-flying_${{ github.run_number }}_amd64.deb
            src-tauri/target/release/bundle/rpm/just-flying_${{ github.run_number }}_x86_64.rpm
            README.md


